language: ruby
rvm:
  - 2.3.1
  - 2.2.5
  - 2.4.0
script: bundle exec rspec spec
cache: bundler
sudo: false
addons:
  code_climate:
    repo_token: faab867977f6f8d51456660b94bb2117f374a7a371102c3601a1d5ac256dafe3
